default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: 'my_app_development'

test:
  <<: *default
  database: 'my_app_test'

production:
  adapter: postgresql
  database: my_database_production
  pool: 5
  timeout: 5000
